currently works

diff --git a/week1/lab0/Makefile b/week1/lab0/Makefile
--- a/week1/lab0/Makefile
+++ b/week1/lab0/Makefile
@@ -4,34 +4,34 @@ CC=gcc
 CFLAGS = -g
 
 all:
-	gcc -g lab0.c -o lab0
+	@gcc -g lab0.c -o lab0
 
 check:	all goodinput goodoutput badoutput inandout noinandnoout canopen catchtest badinput
 
 goodinput:
-	echo "haha haha" > test.txt
-	./lab0 --input=test.txt > output2.txt
-	if [ $$ -eq 0 ] ;\
+	@echo "haha haha" > test.txt
+	@./lab0 --input=test.txt > output2.txt
+	@if [ $$? -eq 0 ] ;\
 	then \
 		echo "Passed: Proper input.\n" ;\
 	else \
 		echo "Failed: Proper input.\n" ;\
 	fi
-	rm output2.txt
+	@rm output2.txt
 
 goodoutput:
-	./lab0 --output=out.txt < test.txt
-	if [ $$? -eq 0 ] ;\
+	@./lab0 --output=out.txt < test.txt
+	@if [ $$? -eq 0 ] ;\
 	then \
 		echo "Passed: Proper output.\n" ;\
 	else \
 		echo "Failed: Proper output.\n" ;\
 	fi
-	rm out.txt
+	@rm out.txt
 
 inandout:
-	./lab0 --input=test.txt --output=out.txt
-	if [ $$? -eq 0 ] ;\
+	@./lab0 --input=test.txt --output=out.txt
+	@if [ $$? -eq 0 ] ;\
 	then \
 		echo "Passed: Proper input and output.\n" ;\
 	else \
@@ -40,39 +40,39 @@ inandout:
 	diff test.txt out.txt > changes.txt ;\
 	if [ -s changes.txt ] ;\
 	then \
-		echo "Passed: Input and output are the same.\n" ;\
+		echo "Failed: Input and output are the same.\n" ;\
 	else \
-		echo "Failed: Input and output are different.\n" ;\
+		echo "Passed: Input and output are different.\n" ;\
 	fi
-	rm changes.txt out.txt
+	@rm changes.txt out.txt
 
 
 noinandnoout:
-	./lab0 < test.txt > out.txt
-	if [ $$? -eq 0 ] ;\
+	@./lab0 < test.txt > out.txt
+	@if [ $$? -eq 0 ] ;\
 	then \
 		echo "Passed: no input and no output test.\n" ;\
 	else \
 		echo "Failed: no input and no output test.\n" ;\
 	fi
-	rm out.txt
+	@rm out.txt
 
 
 badoutput:
-	touch out.txt
-	chmod 444 out.txt 
-	./lab0 --output=out.txt < test.txt ;\
+	@touch out.txt
+	@chmod 444 out.txt 
+	@./lab0 --output=out.txt < test.txt ;\
 	if [ $$? -eq 3 ] ;\
 	then \
 		echo "Passed: Bad output detected.\n" ;\
 	else \
 		echo "Failed: Bad output detected.\n" ;\
 	fi
-	rm -f out.txt
+	@rm -f out.txt
 
 canopen:
-	./lab0 --input=test.txt ;\
-	if [ $$? -eq 1 ] ;\
+	@./lab0 --input=test.txt ;\
+	if [ $$? -eq 0 ] ;\
 	then \
 		echo "Passed: Can open file.\n" ;\
 	else \
@@ -80,19 +80,19 @@ canopen:
 	fi
 
 badinput:
-	touch in.txt
-	chmod 000 in.txt
-	./lab0 --input=in.txt ;\
+	@touch in.txt
+	@chmod 000 in.txt
+	@./lab0 --input=in.txt ;\
 	if [ $$? -eq 2 ] ;\
 	then \
 		echo "Passed: Detected unopenable file.\n" ;\
 	else \
 		echo "Failed: Detected unopenable file.\n" ;\
 	fi
-	rm -f in.txt test.txt
+	@rm -f in.txt test.txt
 
 catchtest:
-	./lab0 --segfault --catch;\
+	@./lab0 --segfault --catch;\
 	if [ $$? -eq 4 ] ;\
 	then \
 		echo "Passed: Caught segfault.\n" ;\
@@ -101,7 +101,7 @@ catchtest:
 	fi
 
 clean:
-	rm -f lab0 *.txt *.tar.gz
+	@rm -f lab0 *.txt *.tar.gz
 
 dist:
-	tar -czvf lab0-204577214.tar.gz Makefile lab0.c backtrace.png breakpoint.png README
+	@tar -czvf lab0-204577214.tar.gz Makefile lab0.c backtrace.png breakpoint.png README
